CI Test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -75,24 +75,24 @@ jobs:
   build-backend:
     docker:
       - image: circleci/openjdk
-      - image: circleci/mysql
-        environment:
-          MYSQL_ROOT_PASSWORD: root
-          MYSQL_DATABASE: restapi
-          MYSQL_USER: user
-          MYSQL_PASSWORD: password
+      # - image: circleci/mysql
+      #   environment:
+      #     MYSQL_ROOT_PASSWORD: root
+      #     MYSQL_DATABASE: restapi
+      #     MYSQL_USER: user
+      #     MYSQL_PASSWORD: password
     steps:
       - checkout
-      - run:
-          name: Waiting for MySQL to be ready
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z 127.0.0.1 3306 && echo Success && exit 0
-              echo -n .
-              sleep 3
-            done
-            echo Failed waiting for MySQL && exit 1
+      # - run:
+      #     name: Waiting for MySQL to be ready
+      #     command: |
+      #       for i in `seq 1 10`;
+      #       do
+      #         nc -z 127.0.0.1 3306 && echo Success && exit 0
+      #         echo -n .
+      #         sleep 3
+      #       done
+      #       echo Failed waiting for MySQL && exit 1
       - run:
           name: Back-end build
           command: |
@@ -472,18 +472,18 @@ jobs:
 workflows:
   default:
     jobs:
-      # - build-frontend
+      - build-frontend
       - build-backend
-      # - test-frontend:
-      #     requires: [build-frontend]
-      # - lint-frontend:
-      #     requires: [build-frontend]
-      # # - test-backend:
-      # #     requires: [build-backend]
-      # # - scan-backend:
-      # #     requires: [build-backend]
-      # - scan-frontend:
-      #     requires: [build-frontend]
+      - test-frontend:
+          requires: [build-frontend]
+      - lint-frontend:
+          requires: [build-frontend]
+      # - test-backend:
+      #     requires: [build-backend]
+      # - scan-backend:
+      #     requires: [build-backend]
+      - scan-frontend:
+          requires: [build-frontend]
       # - deploy-infrastructure:
       #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
       #     filters:
